### ISSUE TITLE
CiaB 7.0.1: bootstrap fails on traefik 

### ISSUE THREAD

**Issue by garloff** [osism/cloud-in-a-box#261]
```shell
cd /opt/configuration/environments/manager
./run.sh traefik
[...]

TASK [osism.services.traefik : Create traefik external network] ************************************************************************
ok: [manager.systems.in-a-box.cloud]

TASK [osism.services.traefik : Copy docker-compose.yml file] ***************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: {{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. {{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'
fatal: [manager.systems.in-a-box.cloud]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. {{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'. 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_vlan100'"}

PLAY RECAP *****************************************************************************************************************************
manager.systems.in-a-box.cloud : ok=8    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by garloff** [comment]
Looks correct to me ...
```yaml
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
---
network:
  version: 2
  renderer: networkd

  bonds:
    {}


  bridges:
    {}


  ethernets:
    eno1np0:
        dhcp4: true


  tunnels:
    {}


  vlans:
    vlan100:
        addresses:
        - 192.168.16.10/24
        id: 100
        link: eno1np0
    vlan101:
        id: 101
        link: eno1np0


  vrfs:
    {}
```
